spring:
  application:
    name: CoffeeShop API
  servlet:
    context-path: /CoffeeShop
  jpa:
    open-in-view: false

springdoc:
  swagger-ui:

    # If you have JS, add customJsUrl here
    path: /swagger-ui.html
